import Head from "next/head";
import Script from "next/script";

export default function HeadPartial() {
  return (
    <>
      <Head>
        <title>MrlolDev</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/gem.svg" />
      </Head>
      <Script
        src="https://kit.fontawesome.com/05bb22a118.js"
        crossOrigin="anonymous"
      ></Script>
    </>
  );
}
